name: Dev Infra

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  infra:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v3

      - name: Terraform init
        working-directory: envs/dev
        run: terraform init -reconfigure

      - name: Terraform validate
        working-directory: envs/dev
        run: terraform validate

      - name: Terraform plan
        working-directory: envs/dev
        run: terraform plan

      - name: Terraform apply
        working-directory: envs/dev
        run: terraform apply -auto-approve